#+TITLE: Notes on Finite Volume Method MME 9710
#+AUTHOR: Max Le
#+LATEX_HEADER: \usepackage[a4paper,margin=1in, truedimen]{geometry} \usepackage{graphicx} \usepackage{amssymb}
#+LATEX_CLASS_OPTIONS: [14pt]
#+LATEX_HEADER: \usepackage{amsfonts} \usepackage{amsmath}
#+DATE: \today
#+OPTIONS: tex:t 

* CHAPTER 1: INTRODUCTION
** Generic Conservation Equation
   Consider the following generic conservation equation:
   #+begin_export latex
   \begin{equation}
   \frac{\partial \phi}{\partial t} + \nabla \cdot (\textbf{u}\phi) + \nabla \cdot \textbf{J}_\phi = S_\phi
   \end{equation}
   #+end_export
   where the variables are defined as:
  
  
 | *Variable*          | *Description*                      |
 |-------------------+----------------------------------|
 | $\phi$            | Generic variable                 |
 | $t$               | Time                             |
 | *u*                 | Velocity vector                  |
 | $\textbf{J}_\phi$ | Diffusive flux of $\phi$         |
 | $S_\phi$          | Volumetric source/sink of $\phi$ |
 |-------------------+----------------------------------|

** Mass Conservation Equation
   Setting $\phi = \rho$, where $\rho$ is the density. Also, mass conservation of a =continuous= substance does not
   have diffusive flux => $\textbf{J}_\rho = 0$.
   #+begin_export latex
   \begin{equation}
   \frac{\partial \rho}{\partial t} + \nabla \cdot (\textbf{u}\rho) = S_\rho
   \end{equation}
   #+end_export

   *Notes*:
   * For incompressible, constant density flow:
     * $\frac{\partial \rho}{\partial t} = 0$
     * $\nabla \cdot (\textbf{u}\rho) = \rho \nabla \cdot \textbf{u}$
     * Result in: $\nabla \cdot \textbf{u} = \frac{S_\rho}{\rho}$
     * And if no source/sink => $\nabla \cdot \textbf{u} = 0$

** Momentum Conservation Equation
   Setting $\phi = \rho \textbf{u}$. Diffusive flux term $\textbf{J}_\textbf{u} = -\nabla \cdot \sigma$, where
   $\sigma$ is the fluid stress tensor. 

   #+begin_export latex
   \begin{equation}
   \frac{\partial (\rho \textbf{u})}{\partial t} + \nabla \cdot (\rho \textbf{uu})  = \nabla \cdot \sigma +
   S_\textbf{u}
   \end{equation}
   #+end_export
   The stress tensor, $\sigma$ can be expressed in terms of pressure ($p$) and viscous stress tensor ($\tau$)
   and identity matrix, $I$:
  
   #+begin_export latex
   \begin{equation}
   \sigma = -p\textbf{I} + \tau
   \end{equation}
   #+end_export
   After substituting, we get the following form of the momentum conservation equation:
   #+begin_export latex
   \begin{equation}
   \frac{\partial (\rho \textbf{u})}{\partial t} + \nabla \cdot (\rho \textbf{uu})  = -\nabla p + \nabla \cdot \tau
   + S_\textbf{u}
   \end{equation}
   #+end_export
   For incompressible Newtonian fluid, we can rewrite $\tau$ in terms of the dynamic viscosity, $\mu$
   $\tau = \mu(\nabla \textbf{u}+\nabla \textbf{u}^T)$.  Thus, a momentum conservation equation for _incompressible_,
   _Newtonian_ fluid, _constant velocity_:

   #+begin_export latex
   \begin{equation}
   \frac{\partial (\rho \textbf{u})}{\partial t} + \nabla \cdot (\rho \textbf{uu})  = -\nabla p + \mu \nabla^2
   \textbf{u} + S_\textbf{u}
   \end{equation}
   #+end_export

** Energy Conservation Equation
   Setting $\phi = \rho h$ with $h$ being the specific enthalpy of a substance at a given state. Thus, the unit for $\phi$ is
   energy per unit volume. The diffusive flux is given by Fourier's law: $J = -k \nabla \textbf{T}$ with $k$ is the thermal conductivity.
   #+begin_export latex
   \begin{equation}
   \frac{\partial (\rho h)}{\partial t} + \nabla \cdot (\rho \textbf{u} h)  = \nabla \cdot (k \nabla \textbf{T}) +
   S_h
   \end{equation}
   #+end_export

   If we assume:
   * incompressible flow
   * constant specific heat capacity, $h = c_p \textbf{T}$
   * constant thermophysical properties ($k$ and $\rho$)
   * no source term
  
   #+begin_export latex
   \begin{equation}
   \frac{\partial (\textbf{T})}{\partial t} + \nabla \cdot (\textbf{u T})  = \alpha \nabla ^2 \textbf{T}
   \end{equation}
   #+end_export

   where $\alpha = \frac{k}{\rho c_p}$ is the thermal diffusivity. 

** Discretization of the Generic Conservation Equation
   Our generic variable, $\phi$ is a function of of spatial and time: $\phi = \phi (\textbf{x},t)$, where
   $\textbf{x} = (x,y,z)$. Note that spatial variable can be influenced "_one way_" or "_two way_", i.e.
   * One way: changes in $\phi$ only occur due to change on one side of that location
   * Two way: changes in $\phi$ occur due to changes on both side of that location. 
  For example, heat conduction in the image below at cell $i$ is influenced by cell $i-1$ and
  $i+1$. Here, $\textbf{x}$ is a _two way_ coordinate for heat conduction

  #+begin_export latex
  \begin{center}
  \includegraphics[scale=0.2]{pic/heatTwoway.png}
  \end{center}
  #+end_export
  Now consider transient heat convection/conduction. The temperature at any given time is influenced by
  existing conditions before that point *in time*. Here, $\textbf{t}$ is a _one way_ coordinate for transient heat conduction/convection

  #+begin_export latex
  \begin{center}
  \includegraphics[scale=0.2]{pic/heatOneway.png}
  \end{center}
  #+end_export
  Recall our generic conservation equation:
  #+begin_export latex
  \begin{equation*}
  \frac{\partial \phi}{\partial t} + \nabla \cdot (\textbf{u}\phi) + \nabla \cdot \textbf{J}_\phi = S_\phi
  \end{equation*}
  #+end_export
  We consider the diffusion term or *elliptic PDE* :  $\boxed{\nabla \cdot \textbf{J}_\phi}$ to be _two-way in space_\\
  Likewise, the convection term or *parabolic PDE* :  $\boxed{\nabla \cdot (\textbf{u}\phi)}$ to be _one-way in space_ 

** Main idea behind Discretization
   Our goal is to:
   * replace the PDEs' continuous solution with _discrete_ solution, at _specific location_ that approximates the continuous
     solution suitably.
   For finite volume:
   1. domain is split into _non overlapping finite_ regions that fill the domain
   2. the discrete point is at the _centroid_ of each control volume with volume $V_p$, at position $\textbf{x}_p$
   3. surround these cells, we have the "faces". At the center of these "faces", we have the integration point at position
       $\textbf{x}_{ip}$
   4. the governing equations are then integrated over a control volume, where surface flux terms and volume source terms are
      balanced. 
      #+begin_export latex
      \begin{center}
      \includegraphics[scale=0.2]{pic/finiteVolumeElement.png}
      \end{center}
      #+end_export
** Determine Cell Centre + Face Integration Points
   _Cell centre_ => location of _solution_ variables.\\
   Points on _face_ => _fluxes_ are evaluated.\\
   Consider a volume integral of a quantity $\phi$, we may express this integral in discrete form as follow:
   #+begin_export latex
   \begin{equation}
   \int_V \phi dV \approx \phi_P V_P 
   \end{equation}
   #+end_export
   where $\phi_P$ is the value of $\phi$ at some internal within $V$ and $V_P$ is total volume of the cell:
   #+begin_export latex
   \begin{equation}
   V_P = \int_V dV 
   \end{equation}
   #+end_export
 To prove the above result, we expand $\phi$ in a Taylor series about the point $P$.
 #+begin_export latex
 \begin{equation}
 \phi \approx \phi_P + \nabla \phi_P (\textbf{x} - \textbf{x}_P) + \nabla^2 \phi_P (\textbf{x}-\textbf{x}_P)(\textbf{x}-\textbf{x}_P) + .... O(\delta^3) 
 \end{equation}
 #+end_export
 with $\delta$ being the characteristic grid spacing. Substitute this into our assumed expression for $V_P$:
 #+begin_export latex
 \begin{equation}
 \int_V \phi dV \approx \int_V [\phi_P + \nabla \phi_P (\textbf{x} - \textbf{x}_P) + \nabla^2 \phi_P (\textbf{x}-\textbf{x}_P)(\textbf{x}-\textbf{x}_P) + .... O(\delta^3)]dV 
 \end{equation}
 #+end_export
 We note that $\phi_P$ and its derivatives are constants:
 #+begin_export latex
 \begin{equation}
 \int_V \phi dV \approx \phi_P dV + \nabla \phi_P \int_V (\textbf{x}-\textbf{x}_P) dV + \nabla^2 \phi_P \int_V (\textbf{x}-\textbf{x}_P)(\textbf{x}-\textbf{x}_P)dV + .... O(\delta^3) 
 \end{equation}
 #+end_export
 Because our $\textbf{x}_P$ point is at centroid, so $\int_V (\textbf{x}-\textbf{x}_P) dV = 0$. Likewise, the last term is also neglected,
 resulting in:
 #+begin_export latex
 \begin{equation}
 \int_V \phi dV \approx [\phi_V + O(\delta^2)]V_P
 \end{equation}
 #+end_export
 This means that there is a second order error when approximating the cell volume in this way.  This is OK because the accuracy of
 the method is also second order.\\
 *Note*: If our $\textbf{x}_P} does not lie at the centroid of the cell. The second term,$\int_V (\textbf{x}-\textbf{x}_P) dV$ does not go
 to zero, making our approximation to be 1st order, which is worse. 
** Transient term
   Here we deal with the transient term, $\frac{\partial \phi}{t}$. Discretization of this term relies on:
   * order of accuracy
   * implicit vs explicit
   The idea is to integrate this term over control volume $V_P$ and some time step $\Delta t = t_1 - t_0$ to get
   the formula for the discretization.
   #+begin_export latex
   \begin{equation}
   \int_{t_0}^{t_1} \int_V \frac{\partial \phi}{\partial t}dVdt \approx (\phi V_P)^{t_1} - (\phi V_P)^{t_0} 
   \end{equation}
   #+end_export
** Advection term
   Here we deal with the advection term, $\nabla \cdot (\textbf{u} \phi)$. Similar to the transient term, the formula for the
   discretization can be obtained by integrating over the control volume $V_P$. We also employ Gauss' theorem to convert
   _volume integral_ to _surface integral_:
   #+begin_export latex
   \begin{equation}
   \int_V \nabla \cdot (\textbf{u}\phi)dV = \int_S (\textbf{u}\phi) \cdot \textbf{n}dS
   \end{equation}
   #+end_export
   For the surface integral, we approximate by summing up over the faces surrounding the cell, each with area $A_{ip}$.
   #+begin_export latex
   \begin{equation}
   \int_S (\textbf{u}\phi) \cdot \textbf{n}_{ip}dS \approx \sum_{i=0}^{N_{ip}-1} \textbf{u}_{ip} \cdot \textbf{n}_{ip} \phi_{ip}A_{ip}
   \end{equation}
   #+end_export
   *Note*:
   * using C program notation, so we sum from 0 till $N_{ip}-1$
   * approximate $\textbf{u}_{ip}$ by many interpolation methods
   * interpolating $\phi_{ip}$ carefully to obtain _stable_ numerical method. 
** Diffusion term
   Now, we deal with the diffusion term, $\nabla \cdot \textbf{J}_\phi$. Similar to the advection term, we integrate over a control
   volume, then apply Gauss' theorem
   #+begin_export latex
   \begin{equation}
   \int_V \nabla \cdot \textbf{J}_\phi dV = \int_S \textbf{J}_\phi \cdot \textbf{n}dS
   \end{equation}
   #+end_export
   Again, the surface integral is approximated as discrete sum over the faces surrounding the cell:
   #+begin_export latex
   \begin{equation}
   \int_S \textbf{J}_\phi \cdot \textbf{n}dS \approx \sum_{i=0}^{N_{ip}-1} \textbf{J}_{\phi, ip} \cdot \textbf{n}_{ip}\textbf{A}_{ip}
   \end{equation}
   #+end_export
   where the flux, $\textbf{J}_{\phi,ip}$ is interpolated from neighboring cell values. 
** Source term
   Recall our source term: $S_\phi$, we assume that the source term is _piecewise continuous_, with one specific value, $S_\phi$,
   being represented by each cell. We can then write:
   #+begin_export latex
   \begin{equation}
   \int_V S_\phi dV \approx S_\phi V_P
   \end{equation}
   #+end_export
   Generally, the source term may depend on $\phi$ so linearization is needed to obtain _stable_ numerical method. 
** Linearization
   With regard to our last point about $J_\phi$, the discretized terms depend non linearly on the solution. This non-linearity
   is caused by:
   * source term depend non linearly on primitive variable, e.g. $J_\phi$.
   * non linearities in the governing equation, e.g. advection term $\nabla \cdot (\textbf{u} \phi)$
   * on non-orthogonal grid, gradient correction terms are needed <= these are non linear.
   To linearize, we assume the governing PDE is represented by the following general differential operator
   #+begin_export latex
 \begin{equation}
 L(\phi^*) = 0
 \end{equation}
   #+end_export
   where:\\
   - $\phi^*$ = the continuous solution to the PDE
   - Note that to solve a PDE using finite volume, the continuous solution $\phi^*$ is approximated by the discrete solution vector
     $\phi \in \mathbb{R}$ on $N$ number of control volume. Our PDE is then integrated over each control volume and each term in the
     governing equation is approximated using the discrete solution $\phi$
   - Of course, the numerical solution will not satisfy the discretized equation exactly; rather we will have a residual,
     $\textbf{r} \in \mathbb{R}^N$.
   We expand the residual about the solution $\phi_i$ at iteration $i$, and find the solution where $r = 0$:
   #+begin_export latex
 \begin{equation}
 \textbf{r}(\phi_i) + \left. \frac{\partial \textbf{r}}{\partial \phi}\right|_{\phi_i}(\phi - \phi_i) = 0
 \end{equation}
   #+end_export
   We define the *Jacobian of the residual vector* as:
   #+begin_export latex
   \begin{equation}
   \textbf{J}(\phi) = \frac{\partial \textbf{r}}{\partial \phi}
   \end{equation}
   #+end_export
   We use this to update according to fix point iteration:
   #+begin_export latex
   \begin{equation}
   \phi = \phi_i + \Delta \phi_i
   \end{equation}
   #+end_export
   where:
   #+begin_export latex
   \begin{equation}
   \Delta \phi = (\phi - \phi_i)
   \end{equation}
   #+end_export
   and:
   #+begin_export latex
   \begin{equation}
   \textbf{J}(\phi_i)\Delta \phi = -\textbf{r}(\phi_i)
   \end{equation}
   #+end_export
   The remaining unknowns are: the residual vector $\textbf{r}$ and Jacobian matrix $\textbf{J}(\phi_i)$.\\
   *Note*: we can express the linear system for a control volume P as:
   #+begin_export latex
   \begin{equation}
   a_P\delta \phi_P + \sum_{nb} a_{nb}\delta \phi_{nb} = -r_P
   \end{equation}
   #+end_export
   where $nb$ is sum over all neighboring cells.  The coefficients are defined as:
   #+begin_export latex
   \begin{align}
   a_P &= \frac{\partial r_P}{\partial \phi_P}\\
   a_{nb} &= \frac{\partial r_P}{\partial \phi_{nb}}
   \end{align}
   #+end_export

   #+begin_export latex
   \clearpage
   #+end_export
* CHAPTER 2: STEADY DIFFUSION EQUATION
** Problem Definition
   We consider the solution of a _steady_, _1D_ heat diffusion equation
   #+begin_export latex
   \begin{equation}
   -k \nabla^2 T - S = 0
   \end{equation}
   #+end_export
** Discretization
   Recall our diffusion term can be discretized as:
   #+begin_export latex
   \begin{equation}
   \int_S \textbf{J} \cdot \textbf{n} dS \approx \sum_{i=0}^{N_{ip}-1} \textbf{J}_{ip}\cdot \textbf{n}_{ip}A_{ip}
   \end{equation}
   #+end_export
   Our flux $\textbf{J}$ here is the _diffusive_ flux, so: $\textbf{J} = -k \nabla T$. Thus:
   #+begin_export latex
   \begin{equation}
   \int_S \textbf{J} \cdot \textbf{n} dS \approx -\sum_{i=0}^{N_{ip}-1} k_{ip} \nabla T_{ip}  \cdot \textbf{n}_{ip}A_{ip}
   \end{equation}
   #+end_export
   We assume constant thermal conductivity, $k_{ip} = k$. A 1D control volume, with West/East faces and unit vectors drawn, is shown below:
  #+begin_export latex
  \begin{center}
  \includegraphics[scale=0.2]{pic/heat1D_CV.png}
  \end{center}
  #+end_export
  Since we are in 1D, our unit vector is in the $\textbf{i}$ only.\\
  Thus, $\nabla T \cdot \textbf{n} = \nabla T \cdot \textbf{i}$.\\
  But, $\nabla T \cdot \textbf{i} = \left < \frac{\partial T}{\partial x} \textbf{i} + \frac{\partial T}{\partial y} \textbf{j} + \frac{\partial T}{\partial z} \textbf{k}
  \right > \cdot \left <1 \textbf{i} + 0 \textbf{j} + 0 \textbf{k}    \right> = \frac{\partial T}{\partial x}$. \\
  With these points in mind, the discretization for the diffusion term is simplified to:
  #+begin_export latex
  \begin{equation}
  \int_S \textbf{J} \cdot \textbf{n} dS \approx k \left .\frac{\partial T}{\partial x}\right|_w A_w
  - k \left .\frac{\partial T}{\partial x}\right|_e A_e 
  \end{equation}
  #+end_export
  The diagram below shows the cell locations and the nomenclature for the distance between them, note how $\Delta x$ is center-center
  #+begin_export latex
  \begin{center}
  \includegraphics[scale=0.2]{pic/heat1D_cell.png}
  \end{center}
  #+end_export
  We apply _finite differences_ to the derivatives in the diffusion term, i.e.:
  #+begin_export latex
  \begin{equation}
  k \left .\frac{\partial T}{\partial x}\right|_w A_w - k \left .\frac{\partial T}{\partial x}\right|_e A_e
  = k\frac{T_P-T_W}{\Delta x_{WP}}A_w - k\frac{T_E-T_P}{\Delta x_{PE}}A_e
  \end{equation}
  #+end_export
  Our discretized source term is simply:
  #+begin_export latex
  \begin{equation}
  \int_V SdV \approx S_PV_P
  \end{equation}
  #+end_export
  where $S_P$ = value of source term *within* the cell, and $V_P$ = cell volume.\\
  Put everything on one side, we can form the _residual equation_ for the cell $\textbf{P}$ as:
  #+begin_export latex
  \begin{equation}
  r_P = - k\frac{T_E-T_P}{\Delta x_{PE}}A_e + k\frac{T_P-T_W}{\Delta x_{WP}}A_w - S_PV_P
  \end{equation}
  #+end_export
  or expressing in terms of the diffusive fluxes, $\textbf{F}^d$, through each face:
  #+begin_export latex
  \begin{equation}
  r_P = F_{e}^d - F_{w}^d - S_PV_P
  \end{equation}
  #+end_export
  where:\\
  #+begin_export latex
  \begin{alignat}{2}
  F_{e}^d &= - k\frac{T_E-T_P}{\Delta x_{PE}}A_e &&= -D_e(T_E- T_P)\\
  F_{w}^d &= - k\frac{T_P-T_W}{\Delta x_{WP}}A_w &&= -D_w(T_P- T_W)\\
  D_e &= \frac{kA_e}{\Delta x_{PE}}\\
  D_w &= \frac{kA_w}{\Delta x_{WP}}
  \end{alignat}
  #+end_export
  Our cell residual equation is then:
  #+begin_export latex
  \begin{equation}
  r_P = D_w (T_P-T_W)-D_e(T_E-T_P)-S_PV_P
  \end{equation}
  #+end_export
  The linearized coefficients are then calculated as:
  #+begin_export latex
  \begin{align}
  a_P &= \frac{\partial r_P}{\partial T_P} = D_w + D_e - \frac{\partial S_P}{\partial T_P}V_P\\
  a_W &= \frac{\partial r_P}{\partial T_W} = -D_w\\
  a_E &= \frac{\partial r_P}{\partial T_E} = -D_e
  \end{align}
  #+end_export
  Recall that we can form an algebraic system of equation for each control volume like this:
  #+begin_export latex
  \begin{align}
  a_P\delta \phi_P + \sum_{nb} a_{nb}\delta \phi_{nb} &= -r_P\\
  a_P\delta T_P + a_W\delta T_W + a_E \delta T_E &= -r_P 
  \end{align}
  #+end_export
  The above linear system of equations can be written as as tridiagonal matrix, like this:
  #+begin_export latex
  \begin{center}
  \includegraphics[scale=0.2]{pic/heat1D_tridiagonal.png}
  \end{center}
  #+end_export
  *Note*: The first and last row only has 2 non zero elements each. This is because these are the left most/right most side and they are
  adjacent to the domain boundary. Therefore, special _boundary conditions_ are needed to be set. \\
  In matrix notation, we are solving:
  #+begin_export latex
  \begin{equation}
  \textbf{A}\textbf{x} = \textbf{b}  
  \end{equation}
  #+end_export
  where $\textbf{A}$ is the Jacobian matrix, $\textbf{b} = \textbf{-r}$ is the residual vector, $\textbf{x} = \delta \textbf{T}$
  is the solution correction. At each current iteration $i$, the solution is updated according to:
  #+begin_export latex
  \begin{equation}
  \textbf{T} = \textbf{T}_i + \delta \textbf{T}i
  \end{equation}
  #+end_export
** Source Terms
   Our source term can have many forms, depending on the type of heat source. We will assume /external convection/
   and /radiation exchange/:
   * For external convection:
     #+begin_export latex
     \begin{equation}
     \frac{S_{conv,P}}{V_P} = -hA_0(T_P-T_{\infty,c})
     \end{equation}
     #+end_export
     where:
     - $h$ is the convective coefficient.
     - $A_0$ is external surface area of the cell $P$.
     - $T_P$ is temperature at the centroid of cell $P$.
     - $T_{\infty,c}$ is the ambient temperature for the convection process. 
   * For radiation exchange:
     #+begin_export latex
     \begin{equation}
     \frac{S_{rad}}{V_P} = -\epsilon \sigma A_0(T_P^4 - T_{\infty,r}^4)
     \end{equation}
     #+end_export
     where:
     - $\epsilon$ is the surface emissivity.
     - $\sigma$ is the Stefan-Boltzmann constant.
     - $T_{\infty,r}$ is the surrounding temperature for radiation exchange. 
** Discussion of Discretization Procedure
*** Temperature Profile Assumptions
    When computing the diffusive fluxes through the faces, we assumed a *piecewise-linear profile* for the temperature.
    This ensures that the derivatives are defined at the integration points and provides consistency for flux
    at control-volume faces. For the source term, *piece-wise constant profile* is used, implying a single value of the source
    term in each cell. Note that for piece-wise constant profile, the derivatives are not defined at integration points, due to
    jump discontinuity. So if fluxes will be inconsistent if piecewise-constant profile is used for temperature.
    #+begin_export latex
    \begin{center}
    \includegraphics[scale=0.2]{pic/heat1D_profilePW.png}
    \end{center}
    #+end_export
*** Implementation of Linearization
    In Patakar's method, the solution of the linear system *is* the solution for the variables at the control volume center.\\
    In our method, the solution of the linear system is the *correction* to apply to the previous iteration of the solution. \\
    The correction method is preferred because:
    * at convergence, the solution for the correction goes to zero $\rightarrow$ zero a good initial guess for the linear solver.
    * linear system involves the residual vector. In Patankar's, there are more work to calculate the residual vector.
*** Properties of the Discrete Algebraic Equations
    Recall our algebraic equation for the linear system
    #+begin_export latex
    \begin{equation}
    a_P\delta T_P + a_W\delta T_W + a_E \delta T_E = -r_P 
    \end{equation}
    #+end_export
    In Rule 2, we require that $a_P > 0$ and $a_W, a_E < 0$. The reason for this is if we consider the case with no source,
    and the solution converge, $r_P \rightarrow 0$:
    #+begin_export latex
    \begin{equation}
    a_P\delta T_P = -a_W\delta T_W - a_E \delta T_E  
    \end{equation}
    #+end_export
    Now, suppose both $T_P$ and $T_E$ are pertubed.  If either of these temperatures were to rise, then $T_P$ would also rise.
    Similarly, if either temperatures were to drop, $T_P$ should also drop. Therefore, to ensure correct physical effect, if
    $a_P > 0$ then $a_W, a_E > 0$.\\
    Consider the two cells ($P$ and $E$) below:
    #+begin_export latex
    \begin{center}
    \includegraphics[scale=0.2]{pic/heat1D_cell_combined.png}
    \end{center}
    #+end_export
    At convergence, $r_P = 0$, the equation for the control volume $P$ is:
    #+begin_export latex
    \begin{equation}
    F_{e,P}^d - F_{w,P}^d - S_PV_P = 0
    \end{equation}
    #+end_export
    For the control volume $E$:
    #+begin_export latex
    \begin{equation}
    F_{e,E}^d - F_{w,E}^d - S_EV_E = 0
    \end{equation}
    #+end_export
    Adding these equations together gives:
    #+begin_export latex
    \begin{equation}
    F_{e,P}^d - F_{w,P}^d +  F_{e,E}^d - F_{w,E}^d- S_PV_P - S_EV_E = 0
    \end{equation}
    #+end_export
    Note that $F_{e,P}^d = F_{w,E}^d$ by continuity, i.e. the flux at cell $P$ going eastward should be the same flux going
    from westward at cell $E$. If these are not equal, then it implies that there is a fictuous force at the face, which is
    not reasonable. Therefore, our algebraic equation for control volume $P$ and $E$ becomes:
    #+begin_export latex
    \begin{equation}
     F_{e,E}^d - F_{w,P}^d - S_PV_P - S_EV_E = 0
    \end{equation}
    #+end_export
    The above equation demonstrates integral conservation: a balance of the total source term within the combined control volume with
    the net diffusive flux from that same control volume. In addition, recall the definition of the diffusive flux:
    #+begin_export latex
    \begin{align}
    F_{e,P}^d &= -k \frac{T_E-T_P}{\Delta x_{PE}} A_{e,P}\\
    F_{w,E}^d &= -k \frac{T_E-T_P}{\Delta x_{PE}} A_{w,E}
    \end{align}
    #+end_export
    From the gemeotry of the grid, $A_{e,P} = A_{w,E}$; therefore, it is in fact the two-point finite difference estimation of the
    derivative that cause the fluxes to be equal. This is also due to the piecewise-linear profile that we assume. If we assume a
    *parabolic profile* instead, there is no guarantee that the fluxes would be equal. Instead, we would have:
    #+begin_export latex
    \begin{align}
    F_{e,P}^d &= f(T_W, T_P, T_E)\\
    F_{w,E}^d &= f(T_P, T_E, T_{EE})
    \end{align}
    #+end_export
    This means that the flux through the common face depends on different temperature, so we cannot be sure that the derivative from either
    side is consistent. 
    #+begin_export latex
    \begin{center}
    \includegraphics[scale=0.2]{pic/heat1D_profilePARABOLIC.png}
    \end{center}
    #+end_export
** Implemenation: [[file:1D_heat_diffusion.py][Python code]]
  #+begin_export latex
  \clearpage
  #+end_export
* CHAPTER 3: TRANSIENT 1D HEAT DIFFUSION
** Problem Definition
   In contrast to the steady case, here we are solving the following transient 1D heat diffusion equation
   #+begin_export latex
   \begin{equation}
   \frac{\partial (\rho c_p T)}{\partial t} = k \nabla^2 T + S
   \end{equation}
   #+end_export
   assuming constant $\rho$ and $c_p$
** Discretization
   Integrating the governing equation through space and time yields:
   #+begin_export latex
   \begin{equation}
   \int_{t_0}^{t_1} \int_{V} \frac{(\partial \rho c_p T)}{\partial t} dt dV = \int_{t_0}^{t_1} \int_{V} k \nabla^2 T dt dV + \int_{t_0}^{t_1} \int_{V} S dt dV
   \end{equation}
   #+end_export
   By assuming a timestep $\Delta t = t_1 - t_0$, we also assume that the solution is stored at time levels $t$ and later at $t + \Delta t$. Thus, we can assume various profiles for the integrands as functions of time.  Here, we will examine the following:
   * *Fully explicit*: evaluate the integrands on RHS at initial time level, $t_0 = t$.
   * *Fully implicit*: evaluate the integrands on RHS at final time level, $t_1 = t_0 + \Delta t$
   * *Crank Nicolson*: assume a linear profile of the RHS over the interval $\Delta t$. 
   For the LHS, we interchange the order of integration, which results in this, for a control volume $\textbf{P}$:
   #+begin_export latex
   \begin{equation}
   \int_{t_0}^{t_1} \int_{V} \frac{(\partial \rho c_p T)}{\partial t} dt dV = (\rho c_p T_p)^{t+\Delta t} - (\rho c_p T_p)^t 
   \end{equation}
   #+end_export
   Recall that for the steady case, the diffusive term is the difference in flux. Here, we add a weighting function $w$ to control the assumed variation of the integrand over the timestep. 
   #+begin_export latex
    \begin{equation}
   \int_{t_0}^{t_1} \int_{V} k \nabla^2 T dt dV = -\left [\omega(F_e^d)^{t + \Delta t} + (1-\omega)(F_e^d)^t \right ]\Delta t +
   \left [\omega(F_w^d)^{t + \Delta t} + (1-\omega)(F_w^d)^t \right ]\Delta t
   \end{equation}
   #+end_export
  #+begin_export latex
  \begin{center}
  \includegraphics[scale=0.3]{pic/transientHeat_omega.png}
  \end{center}
  #+end_export
  Grouping the time levels together:
  #+begin_export latex
  \begin{equation}
   \int_{t_0}^{t_1} \int_{V} k \nabla^2 T dt dV = \left[\omega[F_w^d-F_e^d \right ]^{t+\Delta t}\Delta t +
   (1-\omega)\left [F_w^d - F_e^d \right ]^t\Delta t
  \end{equation}
  #+end_export
  Assuming no source term, $S = 0$, constant properties and divide by $\Delta t$, our discretized equation becomes
  #+begin_export latex
  \begin{equation}
 \rho c_p \frac{T_P^{t+\Delta t} - T_P^t}{\Delta t} V_P = \omega \left[F_w^d-F_e^d \right ]^{t+\Delta t} +
   (1-\omega)\left [F_w^d - F_e^d \right ]^t\
  \end{equation}
  #+end_export
  *_Note_*
  * fully implicit and fully explicit are /1st order/ accurate in time.
  * Crank-Nicolson are /2nd order/ accurate in time.
    * but Crank-Nicolson are /less stable/, cause oscillations.
  * Generally, explicit solutions do not require the solution of a system of equations. All diffusive fluxes are calculated using solution values from previous timestep
  * Implicit requires solution of a linear system at current time step. The same is true for Crank-Nicolson, or any scheme where $0<\omega < 1$
** Analysis of Explicit Scheme
   Recall explicit scheme means $\omega = 0$. Our discretized equation becomes:
   #+begin_export latex
   \begin{equation}
   \rho c_p \frac{T_P ^{t+\Delta t}}{\Delta t} V_P = [F_w^d-F_e^d]^t + \rho c_p \frac{T_P^t}{\Delta t}V_P 
   \end{equation}
   #+end_export
   Recall that the fluxes can be defined as:
    #+begin_export latex
   \begin{alignat}{2}
   F_{e}^d &= - k\frac{T_E-T_P}{\Delta x_{PE}}A_e &&= -D_e(T_E- T_P)\\
   F_{w}^d &= - k\frac{T_P-T_W}{\Delta x_{WP}}A_w &&= -D_w(T_P- T_W)\\
   D_e &= \frac{kA_e}{\Delta x_{PE}}\\
   D_w &= \frac{kA_w}{\Delta x_{WP}}
   \end{alignat}
    #+end_export
    Thus, our explicit formulation becomes:
   #+begin_export latex
   \begin{equation}
   \rho c_p \frac{T_P ^{t+\Delta t}}{\Delta t} V_P = D_eT_E^t + D_wT_W^t + \left ( \frac{\rho c_p V_P}{\Delta t} - D_e - D_w \right)T_P^t 
   \end{equation}
   #+end_export
   To get correct physical influence, the coefficient of $T_P^t$ must be positive, to ensure $\uparrow T_P^t$ leads to $\uparrow T_P^{t+\Delta t}$.
   Therefore, our timestep must be selected such that:
   #+begin_export latex
   \begin{equation*}
   \frac{\rho c_p V_P}{\Delta t} \geq D_e + D_w 
   \end{equation*}
   #+end_export
   or
   #+begin_export latex
   \begin{equation*}
   \Delta t \leq \frac{\rho c_p V_P}{D_e + D_w} = \frac{1}{\frac{D_e}{\rho c_p V_P} + \frac{D_w}{\rho c_p V_P} }
   \end{equation*}
   #+end_export
   Simplifying further, we assume $V_P = A\Delta x$ where $A$ is the cross-sectional area of the domain at $P$, and $\Delta x$ is the grid spacing.
   Also assuming $A_e, A_w \approx A$
   #+begin_export latex
   \begin{equation*}
   \frac{D_e}{\rho c_p V_P} \approx \frac{\frac{kA_e}{\Delta x}}{\rho c_p A \Delta x} = \frac{k}{\rho c_p}\frac{1}{\Delta x^2} = \frac{\alpha}{\Delta x^2}
   \end{equation*}
   #+end_export
   The quantity $\frac{\Delta x^2}{\alpha}$ may be interpreted as the timescale associated with conduction through the face.\\
   For uniform grid, $A_e =
   A_w = A$, the timestep restriction is:
   #+begin_export latex
   \begin{equation}
   \Delta t \leq \frac{1}{\frac{\alpha}{\Delta x^2} + \frac{\alpha}{\Delta x^2}} = \frac{\Delta x^2}{2\alpha}
   \end{equation}
   #+end_export
   Note how our timestep is related to the square of the grid size, so the a fine grid will have a very small "$\Delta x^2$".
   #+begin_export latex
   \newpage \noindent
   #+end_export
   To study this, we consider an iron bar with $\alpha = 23.1 \times 10^{-6}$ [$m^2/s$] at various grid sizes:
   #+NAME: explicit_timestep
   |---------------+-----------------|
   | GRID SIZE [m] | TIME STEP [sec] |
   |---------------+-----------------|
   |          0.01 |       2.1645022 |
   |         0.001 |     0.021645022 |
   |        0.0001 |    2.1645022e-4 |
   |       0.00001 |    2.1645022e-6 |
   |---------------+-----------------|
   #+TBLFM: $2=($1^2)/(2*23.1e-6)
   #+begin_src python :var data=explicit_timestep :exports none
     import matplotlib.pyplot as plt
     gridsize = [a[0] for a in data]
     timestep = [a[1] for a in data]
     plt.figsize= (10,6)
     plt.xlabel("GRID SIZE",fontsize=14)
     plt.ylabel("TIME STEP",fontsize=14)
     plt.plot(timestep[1:],gridsize[1:])
     plt.yscale("log")
     plt.xscale("log")
     plt.xticks(fontsize=14)
     plt.yticks(fontsize=14)
     plt.savefig("pic/explicit_timestep.png")
    #+end_src

    #+RESULTS:
    : None

    #+begin_export latex
    \begin{center}
    \includegraphics[scale=0.6]{pic/explicit_timestep.png}
    \end{center}
    #+end_export
    We can quickly see how the timestep restriction gets worse with increasing grid refinement. As a result, implicit methods are more commonly used
    in practice. Exception would be calculation of turbulent flow using direct numerical simulation (DNS). In this case, explicit method are a good choice
    because they are less expensive per timestep, since no linear system must be solved. 
** Analysis of Fully Implicit Scheme
   Setting $\omega = 1$ for implicit scheme. Our discretized equation becomes:
   #+begin_export latex
   \begin{equation}
   \rho c_p \frac{T_P ^{t+\Delta t}-T_P^t}{\Delta t} V_P = [-D_w(T_P-T_W) + D_e(T_E-T_P)]^{t+\Delta t} 
   \end{equation}
   #+end_export
   Drop the superscript $t+\Delta t$ and denotes old value as "o", after rearranging, we have:
   #+begin_export latex
   \begin{equation}
   \left ( \frac{\rho c_p V_P}{\Delta t} + D_w + D_e \right)T_P = D_wT_W + D_eT_E + \frac{\rho c_p V_P}{\Delta t}T_P^o
   \end{equation}
   #+end_export
   We can see that none of the coefficients can be come negative when written out this way. Still, we must ensure the timestep is small enough to resolve
   all transient phenomena. In contrast to this fully implicit scheme, the _Crank-Nicholson scheme_ has no formal restriction on $\Delta t$, but still
   produces *oscillatory* at large $\Delta t$. 
** Derivation of Second Order Implicit Scheme
*** General idea
    We consider integration over a special *space-time control volume*, with:
    - the time faces being located at $t-\Delta t/2, t+ \Delta t/2$
    - the solution values are stored at $t, t - \Delta t, t - 2\Delta t...$.
    #+begin_export latex
    \begin{center}
    \includegraphics[scale=0.3]{pic/cv_2nd_order_implicit.png}
    \end{center}
    #+end_export
    By using the space-time control volume, the RHS of the discretized equation evaluated at time $t$, can be considered as a
    _representative of the entire timesweep_. The advantages are:
    - we do not need to assume a profile in time, e.g. piecewise constant for fully implicit/explicit, piecewise linear for Crank-Nicholson.
    - no need to store old flux value
    - interpolation depends on the face values:
      - if piecewise constant $\rightarrow$ 1st order scheme
      - if piecewise linear $\rightarrow$ 2nd order scheme
*** Derivation
    Integrate the governing equation over the space-time control volume 
    #+begin_export latex
    \begin{equation}
    \int_{t-\Delta t/2}^{t+\Delta t/2} \int_{V} \frac{(\partial \rho c_p T)}{\partial t} dt dV =
    \int_{t-\Delta t/2}^{t+\Delta t/2} \int_{V} k \nabla^2 T dt dV + \int_{t-\Delta t/2}^{t+\Delta t/2} \int_{V} S dt dV
    \end{equation}
    #+end_export
    Resulting in:
    #+begin_export latex
    \begin{equation}
    (\rho c_p T_p V_p)^{t+\Delta t/2} - (\rho c_p T_p V_p)^{t-\Delta t/2} = [F_w^d-F_e^d]^t \Delta t + S_P^t \Delta t V_P
    \end{equation}
    #+end_export
    Divide by $\Delta t$, express the diffusive fluxes in terms of $D_w$ and $D_e$, dropping superscripts $t$ for current time:
    #+begin_export latex
    \begin{equation}
    \frac{(\rho c_p T_P V_P)^{t+\Delta t /2 } - (\rho c_p T_P V_P)^{t-\Delta t /2 }  }{\Delta t} = -D_w (T_P-T_W)
    + D_e (T_E - T_P) + S_P V_P
    \end{equation}
    #+end_export
    LHS is known, for RHS $\rightarrow$ need to specify values for times $t-\Delta t/2 and $t+\Delta t /2$
    - 1st order time integration scheme
      We assume a *piecewise constant* distribution over each timestep between the face values, resulting in:
      #+begin_export latex
      \begin{align*}
      T_P^{t-\Delta t /2 } &= T_P^{t-\Delta t }\\
      T_P^{t+\Delta t /2 } &= T_P^{t}
      \end{align*}
      #+end_export
    - 2nd order time integration scheme
      We assume a *piecewise linear* distribution over each timestep between the face values, resulting in:
      #+begin_export latex
      \begin{align*}
      T_P^{t-\Delta t /2} &= T_P^{t-\Delta t } + \frac{1}{2}(T_P^{t-\Delta t} - T_P^{t-2\Delta t})\\
      T_P^{t+\Delta t /2} &= T_P^{t} + \frac{1}{2}(T_P^{t} - T_P^{t-\Delta t})\\
      \end{align*}
      #+end_export
      This is achieved by doing backward interpolation and then forward interpolation on the face values.
      The schematic below shows these interpolations:
      #+begin_export latex
      \begin{center}
      \includegraphics[scale=0.5]{pic/2nd_order_implicit_interpolation.png}
      \end{center}
      #+end_export
      Substituting these relations to the integrated governing equation's LHS:
      - For 1st order scheme:
	#+begin_export latex
	\begin{equation}
	\frac{(\rho c_p T_P V_P)^{t+\Delta t /2} - (\rho c_p T_P V_P)^{t-\Delta t /2 }}{\Delta t} = \rho c_p V_P \frac{T_P - T_P^o}{\Delta t}
	\end{equation}
	#+end_export
	_Note_:
	- the superscript for current time is dropped, and superscript for $t-\Delta t$ is replaced by _$o$_ for "old value".
	- also that this is exactly the same as the result for the fully implicit scheme.
      - For 2nd order scheme:
	#+begin_export latex
	\begin{equation*}
	\frac{(\rho c_p T_P V_P)^{t+\Delta t /2} - (\rho c_p T_P V_P)^{t-\Delta t /2 }}{\Delta t} =
	\rho c_p V_P \frac{T_P + \frac{1}{2}(T_P - T_P^o) - T_P^o - \frac{1}{2}(T_P^o-T_P^{oo})}{\Delta t}
	\end{equation*}
	#+end_export
	or a more simplified version....
	#+begin_export latex
	\begin{equation}
	\frac{(\rho c_p T_P V_P)^{t+\Delta t /2} - (\rho c_p T_P V_P)^{t-\Delta t /2 }}{\Delta t} =
	\rho c_p V_P \frac{\frac{3}{2}T_P -2T_P^o + \frac{1}{2}T_P^{oo}}{\Delta t}
	\end{equation}
	#+end_export
	_Note_:
	- superscript _$oo$_ is used for time value $t-2\Delta t$.
	- unlike Crank-Nicholson's, flux values at previous timestep *do not need to be solved*.
	  Instead, only temperature values at the *previous two time step* need to be retained. 
*** Other Transient Discretization Schemes
    Some higher order schemes are also used such as:
    - Adams-Bashforth (explicit)
    - Adams-Moulton (implicit)
    - Runge-Kutta (implicit or explicit)
*** Linearization
    Recall the cell residual for steady conduction:
    #+begin_export latex
    \begin{equation*}
    r_P = D_w (T_P - T_W) - D_e (T_E - T_P) - S_PV_P
    \end{equation*}
    #+end_export
    where $D_e = \frac{kA_e}{\Delta x_{PE}}$, and $D_w = \frac{kA_w}{\Delta x_{WP}}$.
    #+begin_export latex
    If we apply 1st order implicit to the transient term:
    \begin{equation*}
    r_P = \rho c_p V_P \frac{T_P-T_P^o}{\Delta t}D_w (T_P - T_W) - D_e (T_E - T_P) - S_PV_P
    \end{equation*}
    #+end_export
    This makes the linearization coefficients to be as follow:
    #+begin_export latex
    \begin{align*}
    a_P &= \frac{\partial r_P}{\partial T_P} = \frac{\rho c_p V_P}{\Delta t} + D_w + D_e - \frac{\partial S_P}{\partial T_P}V_P\\
    a_W &= \frac{\partial r_P}{\partial T_W} = -D_w\\
    a_E &= \frac{\partial r_P}{\partial T_E} = -D_e  
    \end{align*}
    #+end_export
    Similar to before, we can form an algebraic equation for each control volume like this:
    #+begin_export latex
    \begin{equation}
    a_P\delta T_P + a_W\delta T_W + a_E \delta T_E = -r_P 
    \end{equation}
    #+end_export
    If we apply 2nd order implicit temporal scheme instead, then $a_P$ term would look like this:
    #+begin_export latex
    \begin{equation*}
    a_P = \frac{\partial r_P}{\partial T_P} = \frac{3}{2}\frac{\rho c_p V_P}{\Delta t} + D_w + D_e - \frac{\partial S_P}{\partial T_P}V_P
    \end{equation*}
    #+end_export
** Implementation: [[file:1d_heat_diffusion_transient.py][Python code]]
